[package]
name = "sui-mev-private-sui-service"
version = "0.1.0"
edition = "2021"

[dependencies]
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
tokio = { version = "^1.2", features = ["full"] }
reqwest = "0.11"
anyhow = "^1.0"
